apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260507-210308-y6pufu4csqbr-service
spec:
  selector:
    app: enterprise-system-20260507-210308-y6pufu4csqbr
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
